
name: Deploy Tapang App via SSH

on:
  push:
    branches:
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan 31.97.63.16 >> ~/.ssh/known_hosts

      - name: Deploy to Server
        run: | 
         ssh -o StrictHostKeyChecking=no root@31.97.63.16 <<EOF
            set -e  # Stop on errors
            cd /var/www/gubera_sites/Tapang_website
            # Ensure remote is using SSH
            git config --global --add safe.directory /var/www/gubera_sites/Tapang_website
            git reset --hard HEAD
            git clean -fd
            git remote set-url origin git@github.com:Gubera369/Tapang_website.git
            # Set pull strategy
            git config pull.rebase false 
            git pull origin production
            npm install
            npm run build
         EOF
         
